# NumPy 

NumPy (or Numpy) is a Linear Algebra Library for Python, the reason it is so important for Data Science with Python is that almost all of the libraries in the PyData Ecosystem rely on NumPy as one of their main building blocks.

Numpy is also incredibly fast, as it has bindings to C libraries

**Import Numpy**

In [10]:
import numpy as np

**Conversion to arrays : List , Matrix**

In [11]:
list1 = [1,2,3]

In [12]:
type(list1)

list

In [13]:
arr1 = np.array(list1)

In [14]:
arr1

array([1, 2, 3])

In [15]:
type(arr1)

numpy.ndarray

In [16]:
matrix1 = [[1,2,3],[4,5,6],[7,8,9]]

In [17]:
arr2 = np.array(matrix1)

In [18]:
arr2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

**Create arrays (1) : Zeros , Ones , Fives , linspace, Identity**

In [19]:
np.zeros(3)

array([0., 0., 0.])

In [20]:
one = np.ones((3,3))
one

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [21]:
one*5

array([[5., 5., 5.],
       [5., 5., 5.],
       [5., 5., 5.]])

In [23]:
np.linspace(0,10,10)

array([ 0.        ,  1.11111111,  2.22222222,  3.33333333,  4.44444444,
        5.55555556,  6.66666667,  7.77777778,  8.88888889, 10.        ])

In [24]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

**Create arrays (2) : rand , randn ,arange , reshape**

In [25]:
np.random.rand(5,5)

array([[0.32469417, 0.06090378, 0.54470537, 0.09210607, 0.27067575],
       [0.36222255, 0.43260682, 0.02893682, 0.40518699, 0.9807897 ],
       [0.92418867, 0.84991825, 0.46053066, 0.46641229, 0.95799587],
       [0.33367286, 0.10314445, 0.23023145, 0.26366383, 0.48385668],
       [0.16668077, 0.81661994, 0.59042005, 0.47903226, 0.42376404]])

*standard normal distribution : mean 0 variance 1*

In [26]:
np.random.randn(5,5)

array([[-0.09080937, -0.23897593,  0.58269447,  1.58921486,  1.44118837],
       [-1.03174841,  1.45485527, -0.30877067,  0.93537026, -0.84696852],
       [ 0.08411448,  0.6188656 ,  1.35683833, -0.27390726,  0.34343215],
       [-0.01210464, -0.40353702,  0.37760345,  0.64429714, -0.55098958],
       [ 0.77842832,  0.19702097,  3.11383101,  1.80655505,  0.26104681]])

In [29]:
arr1d = np.arange(0,25)
arr1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [31]:
arr1d[2:11]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10])

In [32]:
arr1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [33]:
arr2d = arr1d.reshape(5,5)
arr2d

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

**Array selection**  : 1D , 2D , Slicing , Nested

In [35]:
arr2d[3,1]

16

In [38]:
arr2d[2:4,1:3]

array([[11, 12],
       [16, 17]])

In [39]:
arr1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [37]:
arr1d > 10

array([False, False, False, False, False, False, False, False, False,
       False, False,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True])

In [40]:
arr1d[arr1d>10]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24])

In [41]:
arr2d>17

array([[False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False, False, False],
       [False, False, False,  True,  True],
       [ True,  True,  True,  True,  True]])

In [42]:
arr2d[arr2d>17]

array([18, 19, 20, 21, 22, 23, 24])

**Array operations**: max , cube , sine

In [43]:
arr1d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [44]:
np.max(arr1d)

24

In [46]:
arr1d**3

array([    0,     1,     8,    27,    64,   125,   216,   343,   512,
         729,  1000,  1331,  1728,  2197,  2744,  3375,  4096,  4913,
        5832,  6859,  8000,  9261, 10648, 12167, 13824], dtype=int32)

In [47]:
arr1d**5

array([      0,       1,      32,     243,    1024,    3125,    7776,
         16807,   32768,   59049,  100000,  161051,  248832,  371293,
        537824,  759375, 1048576, 1419857, 1889568, 2476099, 3200000,
       4084101, 5153632, 6436343, 7962624], dtype=int32)

In [48]:
np.sin(arr1d)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
        0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721,
        0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836])